// Generated by Copilot
import type { FC } from 'react';
import { useRef, useEffect } from 'react';
import { Message } from './Message';
import { TypingIndicator } from './TypingIndicator';
import './ChatContainer.css';

export interface MessageData {
    id: string;
    sender: 'user' | 'assistant' | 'system' | 'tool';
    content: string;
    timestamp: Date;
}

interface ChatContainerProps {
    messages: MessageData[];
    isTyping: boolean;
}

export const ChatContainer: FC<ChatContainerProps> = ({ messages, isTyping }) => {
    const messagesEndRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }, [messages, isTyping]);

    return (
        <main className="chat-container">
            <div className="chat-messages">
                {messages.length === 0 && (
                    <div className="empty-state">
                        <div className="empty-icon">💬</div>
                        <h2>Welcome to HAL</h2>
                        <p>Your personal homelab assistant. Ask me anything!</p>
                        <div className="suggestions">
                            <button className="suggestion">What can you do?</button>
                            <button className="suggestion">Check system status</button>
                            <button className="suggestion">List running services</button>
                        </div>
                    </div>
                )}

                {messages.map((msg) => (
                    <Message key={msg.id} message={msg} />
                ))}

                {isTyping && <TypingIndicator />}

                <div ref={messagesEndRef} />
            </div>
        </main>
    );
};
