// Generated by Copilot
import type { FC } from 'react';
import type { MessageData } from './ChatContainer';
import './Message.css';

interface MessageProps {
    message: MessageData;
}

export const Message: FC<MessageProps> = ({ message }) => {
    const formatTime = (date: Date) => {
        return date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' });
    };

    const getSenderLabel = (sender: string) => {
        switch (sender) {
            case 'user': return 'You';
            case 'assistant': return 'HAL';
            case 'system': return 'System';
            case 'tool': return 'Tool';
            default: return sender;
        }
    };

    const getSenderIcon = (sender: string) => {
        switch (sender) {
            case 'user': return '👤';
            case 'assistant': return '🤖';
            case 'system': return 'ℹ️';
            case 'tool': return '🔧';
            default: return '💬';
        }
    };

    return (
        <div className={`message message-${message.sender}`}>
            <div className="message-avatar">
                <span className="avatar-icon">{getSenderIcon(message.sender)}</span>
            </div>

            <div className="message-body">
                <div className="message-header">
                    <span className="message-sender">{getSenderLabel(message.sender)}</span>
                    <span className="message-time">{formatTime(message.timestamp)}</span>
                </div>

                <div className="message-content">
                    {message.content}
                </div>
            </div>
        </div>
    );
};
