"""Tool call notification utilities.

Generated by Copilot.

This module provides utilities for formatting and sending tool call
notifications to communication channels.
"""

import json
import logging
from dataclasses import dataclass
from typing import Any, Optional

logger = logging.getLogger(__name__)

# Telegram message limit is 4096 characters
TELEGRAM_MAX_LENGTH = 4000
# WebUI can handle longer messages
WEBUI_MAX_LENGTH = 10000
# Default truncation length
DEFAULT_MAX_LENGTH = 4000


@dataclass
class ToolCallInfo:
    """Information about a tool call."""
    
    name: str
    args: dict[str, Any]
    
    def format(self, max_length: int = DEFAULT_MAX_LENGTH) -> str:
        """Format the tool call for display.
        
        Args:
            max_length: Maximum length of the formatted string.
            
        Returns:
            Formatted tool call string.
        """
        # Format arguments as compact JSON
        try:
            args_str = json.dumps(self.args, ensure_ascii=False, separators=(',', ':'))
        except (TypeError, ValueError):
            args_str = str(self.args)
        
        # Build the message
        message = f"🔧 **Tool:** `{self.name}`\n"
        
        # Calculate available space for args
        prefix_len = len(message) + len("**Args:** ")
        available = max_length - prefix_len - 10  # Leave some buffer
        
        if len(args_str) > available:
            args_str = args_str[:available] + "..."
        
        message += f"**Args:** `{args_str}`"
        
        return message


@dataclass
class ToolResultInfo:
    """Information about a tool result."""
    
    name: str
    result: Any
    
    def format(self, max_length: int = DEFAULT_MAX_LENGTH) -> str:
        """Format the tool result for display.
        
        Args:
            max_length: Maximum length of the formatted string.
            
        Returns:
            Formatted tool result string.
        """
        # Format result
        try:
            if isinstance(self.result, dict):
                result_str = json.dumps(self.result, ensure_ascii=False, indent=2)
            else:
                result_str = str(self.result)
        except (TypeError, ValueError):
            result_str = str(self.result)
        
        # Build the message
        message = f"✅ **{self.name}** result:\n"
        
        # Calculate available space
        available = max_length - len(message) - 10
        
        if len(result_str) > available:
            result_str = result_str[:available] + "\n...(truncated)"
        
        message += f"```\n{result_str}\n```"
        
        return message


def format_tool_call(
    name: str,
    args: dict[str, Any],
    channel: str = "telegram",
) -> str:
    """Format a tool call for a specific channel.
    
    Args:
        name: The tool name.
        args: The tool arguments.
        channel: The channel type (telegram, webui, etc.)
        
    Returns:
        Formatted tool call string.
    """
    max_length = TELEGRAM_MAX_LENGTH if channel == "telegram" else WEBUI_MAX_LENGTH
    return ToolCallInfo(name=name, args=args).format(max_length)


def format_tool_result(
    name: str,
    result: Any,
    channel: str = "telegram",
) -> str:
    """Format a tool result for a specific channel.
    
    Args:
        name: The tool name.
        result: The tool result.
        channel: The channel type (telegram, webui, etc.)
        
    Returns:
        Formatted tool result string.
    """
    max_length = TELEGRAM_MAX_LENGTH if channel == "telegram" else WEBUI_MAX_LENGTH
    return ToolResultInfo(name=name, result=result).format(max_length)


def truncate_for_channel(text: str, channel: str = "telegram") -> str:
    """Truncate text for a specific channel.
    
    Args:
        text: The text to truncate.
        channel: The channel type.
        
    Returns:
        Truncated text.
    """
    max_length = TELEGRAM_MAX_LENGTH if channel == "telegram" else WEBUI_MAX_LENGTH
    
    if len(text) <= max_length:
        return text
    
    return text[:max_length - 20] + "\n...(truncated)"
