// Generated by Copilot
import { useState, useEffect, useRef, useCallback } from 'react';
import { Header, ChatContainer, InputArea, SessionPicker } from './components';
import type { MessageData } from './components';
import './App.css';

interface WSMessage {
  type: 'message' | 'typing' | 'tool';
  sender?: 'user' | 'assistant' | 'system' | 'tool';
  content?: string;
  timestamp?: string;
  typing?: boolean;
}

interface Session {
  user_id: string;
  session_count: number;
  last_update: string;
}

function App() {
  const [messages, setMessages] = useState<MessageData[]>([]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [isConnected, setIsConnected] = useState(false);
  const [userId, setUserId] = useState(() => 'web_' + Math.random().toString(36).substr(2, 9));
  const [sessions, setSessions] = useState<Session[]>([]);
  const [showSessionPicker, setShowSessionPicker] = useState(false);
  const [newUserId, setNewUserId] = useState('');

  const wsRef = useRef<WebSocket | null>(null);

  // Fetch available sessions
  const fetchSessions = useCallback(async () => {
    try {
      const response = await fetch('/api/sessions');
      const data = await response.json();
      setSessions(data.sessions || []);
    } catch (error) {
      console.error('Failed to fetch sessions:', error);
    }
  }, []);

  const connect = useCallback((targetUserId: string) => {
    // Close existing connection
    if (wsRef.current) {
      wsRef.current.close();
    }

    const protocol = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
    const host = window.location.host;
    const ws = new WebSocket(`${protocol}//${host}/ws/${targetUserId}`);

    ws.onopen = () => {
      setIsConnected(true);
      console.log('WebSocket connected as', targetUserId);
    };

    ws.onclose = () => {
      setIsConnected(false);
      console.log('WebSocket disconnected');
    };

    ws.onerror = (error) => {
      console.error('WebSocket error:', error);
    };

    ws.onmessage = (event) => {
      const data: WSMessage = JSON.parse(event.data);

      if (data.type === 'message' && data.content) {
        const newMessage: MessageData = {
          id: Date.now().toString() + Math.random().toString(36),
          sender: data.sender || 'assistant',
          content: data.content,
          timestamp: data.timestamp ? new Date(data.timestamp) : new Date(),
        };
        setMessages(prev => [...prev, newMessage]);
        setIsTyping(false);
      } else if (data.type === 'typing') {
        setIsTyping(data.typing || false);
      } else if (data.type === 'tool' && data.content) {
        // Tool call notification
        const toolMessage: MessageData = {
          id: Date.now().toString() + Math.random().toString(36),
          sender: 'tool',
          content: data.content,
          timestamp: data.timestamp ? new Date(data.timestamp) : new Date(),
        };
        setMessages(prev => [...prev, toolMessage]);
      }
    };

    wsRef.current = ws;
  }, []);

  useEffect(() => {
    connect(userId);

    return () => {
      if (wsRef.current) {
        wsRef.current.close();
      }
    };
  }, [userId, connect]);

  const switchSession = useCallback((newId: string) => {
    setMessages([]);
    setUserId(newId);
    setShowSessionPicker(false);
  }, []);

  const handleNewSession = useCallback(() => {
    const id = newUserId.trim() || 'web_' + Math.random().toString(36).substr(2, 9);
    switchSession(id);
    setNewUserId('');
  }, [newUserId, switchSession]);

  const sendMessage = useCallback(() => {
    const content = input.trim();
    if (!content || !wsRef.current || wsRef.current.readyState !== WebSocket.OPEN) return;

    // Add user message immediately
    const userMessage: MessageData = {
      id: Date.now().toString() + Math.random().toString(36),
      sender: 'user',
      content,
      timestamp: new Date(),
    };
    setMessages(prev => [...prev, userMessage]);

    // Send to server
    wsRef.current.send(JSON.stringify({ type: 'message', content }));
    setInput('');
    setIsTyping(true);
  }, [input]);

  const forgetSession = useCallback(() => {
    if (!wsRef.current || wsRef.current.readyState !== WebSocket.OPEN) return;
    wsRef.current.send(JSON.stringify({ type: 'forget' }));
    setMessages([]);
  }, []);

  const handleSessionClick = useCallback(() => {
    fetchSessions();
    setShowSessionPicker(true);
  }, [fetchSessions]);

  return (
    <div className="app">
      <Header
        userId={userId}
        isConnected={isConnected}
        onSessionClick={handleSessionClick}
      />

      {showSessionPicker && (
        <SessionPicker
          sessions={sessions}
          currentUserId={userId}
          newUserId={newUserId}
          onNewUserIdChange={setNewUserId}
          onSelectSession={switchSession}
          onCreateSession={handleNewSession}
          onClose={() => setShowSessionPicker(false)}
        />
      )}

      <ChatContainer
        messages={messages}
        isTyping={isTyping}
      />

      <InputArea
        value={input}
        onChange={setInput}
        onSend={sendMessage}
        onForget={forgetSession}
        isConnected={isConnected}
      />
    </div>
  );
}

export default App;
